# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

CMakeFiles/main.dir/f_copy.cpp.o: ../f_copy.cpp
CMakeFiles/main.dir/f_copy.cpp.o: ../f_copy.h

CMakeFiles/main.dir/main.cpp.o: ../f_copy.h
CMakeFiles/main.dir/main.cpp.o: ../main.cpp

