# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "demo01_record_writer",
    srcs = ["demo01_record_writer.cc"],
    deps = ["//cyber",
            "//cyber/demo_base_proto:student_cc"],
)

cc_binary(
    name = "demo02_record_reader",
    srcs = ["demo02_record_reader.cc"],
    deps = ["//cyber",
            "//cyber/demo_base_proto:student_cc"],
)
