// Generated by gencpp from file study_msgs/StudyMsg.msg
// DO NOT EDIT!


#ifndef STUDY_MSGS_MESSAGE_STUDYMSG_H
#define STUDY_MSGS_MESSAGE_STUDYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace study_msgs
{
template <class ContainerAllocator>
struct StudyMsg_
{
  typedef StudyMsg_<ContainerAllocator> Type;

  StudyMsg_()
    : detail()
    , id(0)  {
    }
  StudyMsg_(const ContainerAllocator& _alloc)
    : detail(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _detail_type;
  _detail_type detail;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::study_msgs::StudyMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::study_msgs::StudyMsg_<ContainerAllocator> const> ConstPtr;

}; // struct StudyMsg_

typedef ::study_msgs::StudyMsg_<std::allocator<void> > StudyMsg;

typedef boost::shared_ptr< ::study_msgs::StudyMsg > StudyMsgPtr;
typedef boost::shared_ptr< ::study_msgs::StudyMsg const> StudyMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::study_msgs::StudyMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::study_msgs::StudyMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::study_msgs::StudyMsg_<ContainerAllocator1> & lhs, const ::study_msgs::StudyMsg_<ContainerAllocator2> & rhs)
{
  return lhs.detail == rhs.detail &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::study_msgs::StudyMsg_<ContainerAllocator1> & lhs, const ::study_msgs::StudyMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace study_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::study_msgs::StudyMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::study_msgs::StudyMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_msgs::StudyMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::study_msgs::StudyMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_msgs::StudyMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::study_msgs::StudyMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::study_msgs::StudyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f5528a9204f8b31c9206fc97a4a07bb";
  }

  static const char* value(const ::study_msgs::StudyMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f5528a9204f8b31ULL;
  static const uint64_t static_value2 = 0xc9206fc97a4a07bbULL;
};

template<class ContainerAllocator>
struct DataType< ::study_msgs::StudyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "study_msgs/StudyMsg";
  }

  static const char* value(const ::study_msgs::StudyMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::study_msgs::StudyMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string detail\n"
"int32 id\n"
;
  }

  static const char* value(const ::study_msgs::StudyMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::study_msgs::StudyMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detail);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StudyMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::study_msgs::StudyMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::study_msgs::StudyMsg_<ContainerAllocator>& v)
  {
    s << indent << "detail: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detail);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STUDY_MSGS_MESSAGE_STUDYMSG_H
